CREATE TABLE students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  email VARCHAR(50),
  name VARCHAR(30),
  address VARCHAR(255),
  password VARCHAR(20),
  newsletter INT,
  framework VARCHAR(500),
  sex VARCHAR(1),
  number VARCHAR(45),
  country VARCHAR(10),
  skill VARCHAR(500));
